### ISSUE TITLE
Can not detect any device Intermittent.

### ISSUE THREAD

**Issue by brilliantwf** [ts1/BLEUnlock#13]
MacOS 10.14.6
BLEUnlock 1.8.2

**Comment by ts1** [comment]
Can you explain your problem in more detail?
What is the Mac model, what is the BLE device, what is the expectation and what is the reality?

**Comment by brilliantwf** [comment]
Mac model:Macbook pro 2017
Expectation:Scan and detecte my Bluetooth device(iPhoneXR)
Reality:Device List is empty(I need to restart the Bluetooth service or restart the laptop before my device could appear)

**Comment by ts1** [comment]
Thank you for the details.
This happens occasionally in my environment as well.
It feels like it's become more so, especially since iOS 13.

In my case, the following solves the problem:
- Turn off and turn on Bluetooth on the Mac
- Rebooting the Mac
- Restarting the iPhone

If that doesn't work, try the following:
- Switch the Passive Mode of the BLEUnlock
- Upgrading macOS to the latest

**Comment by ts1** [comment]
This happened to me today, and the only solution was rebooting iPhone.

**Comment by ts1** [comment]
@brilliantwf I added option to set no-signal timeout. If you set it longer, the chance to lose signal should be less.
Please try https://github.com/ts1/BLEUnlock/releases/tag/v1.9.0-beta

**Comment by ts1** [comment]
I believe this issue has been fixed in version 1.9.0, which has more robust active mode.
Feel free to reopen if you still have problems.
