### ISSUE TITLE
Support iBeacon

### ISSUE THREAD

**Issue by pjv** [ts1/BLEUnlock#46]
I don’t know if this is a potential solution to #44, but it would be a solution to android phones not advertising a static mac address. There are any number of apps for Android that let you set them to transmit a BLE iBeacon advertisement. If BLEUnlock had a preference to allow it to scan for iBeacons, it would be able to support use with modern Android devices running such an app.

Here is a project that has macOS code for scanning for iBeacons - the release of the demo app from this project reliably identifies my Android iBeacon:

https://github.com/mlwelles/BeaconScanner

**Comment by ts1** [comment]
Thanks for the information.
I have an iBeacon (real thing) and BLEUnlock supports it and shows the approximate distance.
<img width="299" alt="スクリーンショット 2021-07-22 17 42 37" src="https://user-images.githubusercontent.com/1086528/126612121-49c7b50b-edb8-4d87-8d63-bb10c89a9ca6.png">

And, I tried the BeaconScanner on Monterey and it works!
I wonder why, because the two projects do the basically same thing. (CBCentralManager.scanForPeripherals)
Anyway, there is hope that we can support Monterey.
Thanks again!

**Comment by etrahretep** [comment]
Oh yes please! Missing it daily!

**Comment by ts1** [comment]
I close this issue because iBeacon is already supported.
Thanks to @pjv for the information about BeaconScanner, Monterey support has progressed a bit (not yet completed though).
Discussion about Monterey will be continued in #44.
